Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64" 
  config.vm.hostname = "servidorDHCP"
  
  # Configuración de red privada
  config.vm.network :private_network, 
    libvirt__network_name: "red-server",   # Nombre de la red en libvirt
    libvirt__dhcp_enabled: false,         # Deshabilitar DHCP
    ip: "172.22.2.5",                     # IP asignada estáticamente
    libvirt__forward_mode: "none"         # Sin reenvío de tráfico
  
  # Configuraciones adicionales pueden ir aquí
end
